---
- name: setup digital ocean servers
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - digital_ocean: >
        state=present
        command=ssh
        name={{ ssh_name }}
        ssh_pub_key={{ ssh_pub_key }}
      register: sshkey
    - debug: msg="sshkey {{ sshkey }}"

    - digital_ocean: >
        state=present
        command=droplet
        ssh_key_ids={{ sshkey.ssh_key.id }}
        name={{ droplet_name }}
        unique_name=yes
        size_id={{ size_id }}
        region_id={{ region_id }} 
        image_id={{ image_id }}
        wait_timeout=500
      register: droplet
    - debug: msg="droplet {{ droplet }}"

    - digital_ocean_domain: >
        state=present
        name={{ droplet_name }}.host.sampwing.com
        ip={{ droplet.droplet.ip_address }}

#  roles:
#    - { role: common, hosts: droplet.ip_address }
#    - { role: nginx, hosts: droplet.ip_address }
#    - { role: ufw, hosts: droplet.ip_address }
#     
#  post_tasks:
#    - shell: echo "good bye"
