---
- name: setup digital ocean servers
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - digital_ocean: >
        state=present
        command=ssh
        name={{ ssh_name }}
        ssh_pub_key={{ ssh_pub_key }}

    - digital_ocean: >
        state=present
        command=droplet
        name={{ droplet_name }}
        unique_name=yes
        size_id={{ size_id }}
        region_id={{ region_id }} 
        image_id={{ image_id }}
        wait_timeout=500
