---
- name: Remove Droplets 
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - digital_ocean: >
        state=absent
        name={{ droplet_name }}
        unique_name=true
        wait_timeout=500
      register: droplet
    - debug: msg="debug {{ droplet }}"
     
